### ISSUE TITLE
feat(programs): add dart format

### ISSUE THREAD

**Issue by JakobLichterfeld** [numtide/treefmt-nix#231]
As a user I do want to lint my dart code with treefmt multiplexer as well.

[`dart format`](https://dart.dev/tools/dart-format) follows the [formatter-spec](https://treefmt.com/formatter-spec)

Using the `treefmt.toml` configuration works:

```toml
[formatter.dart]
command = "dart"
options = ["format"]
includes = [ "*.dart" ]
```

As i struggled with the config (see https://github.com/numtide/treefmt/issues/410) I would like to add it to the examples
