### ISSUE TITLE
goimports: nix flake check no longer works

### ISSUE THREAD

**Issue by jaredmontoya** [numtide/treefmt-nix#318]
**Describe the bug**
With the new release of GO and goimports in nixpkgs the goimports formatter in treefmt-nix now fails to execute `nix flake check`

**To Reproduce**

1. Create a repository that has go code in it
2. set up a nix flake with treefmt-nix
3. you can use this lockfile to get the old nixpkgs version with the old working go/goimports release
```json
{
  "nodes": {
    "flake-utils": {
      "inputs": {
        "systems": "systems"
      },
      "locked": {
        "lastModified": 1694529238,
        "narHash": "sha256-zsNZZGTGnMOf9YpHKJqMSsa0dXbfmxeoJ7xHlrt+xmY=",
        "owner": "numtide",
        "repo": "flake-utils",
        "rev": "ff7b65b44d01cf9ba6a71320833626af21126384",
        "type": "github"
      },
      "original": {
        "owner": "numtide",
        "repo": "flake-utils",
        "type": "github"
      }
    },
    "gomod2nix": {
      "inputs": {
        "flake-utils": "flake-utils",
        "nixpkgs": [
          "nixpkgs"
        ]
      },
      "locked": {
        "lastModified": 1733668782,
        "narHash": "sha256-tPsqU00FhgdFr0JiQUiBMgPVbl1jbPCY5gbFiJycL3I=",
        "owner": "nix-community",
        "repo": "gomod2nix",
        "rev": "514283ec89c39ad0079ff2f3b1437404e4cba608",
        "type": "github"
      },
      "original": {
        "owner": "nix-community",
        "repo": "gomod2nix",
        "type": "github"
      }
    },
    "nixpkgs": {
      "locked": {
        "lastModified": 1736344531,
        "narHash": "sha256-8YVQ9ZbSfuUk2bUf2KRj60NRraLPKPS0Q4QFTbc+c2c=",
        "owner": "nixos",
        "repo": "nixpkgs",
        "rev": "bffc22eb12172e6db3c5dde9e3e5628f8e3e7912",
        "type": "github"
      },
      "original": {
        "owner": "nixos",
        "ref": "nixos-unstable",
        "repo": "nixpkgs",
        "type": "github"
      }
    },
    "root": {
      "inputs": {
        "gomod2nix": "gomod2nix",
        "nixpkgs": "nixpkgs",
        "systems": "systems_2",
        "treefmt-nix": "treefmt-nix"
      }
    },
    "systems": {
      "locked": {
        "lastModified": 1681028828,
        "narHash": "sha256-Vy1rq5AaRuLzOxct8nz4T6wlgyUR7zLU309k9mBC768=",
        "owner": "nix-systems",
        "repo": "default",
        "rev": "da67096a3b9bf56a91d16901293e51ba5b49a27e",
        "type": "github"
      },
      "original": {
        "owner": "nix-systems",
        "repo": "default",
        "type": "github"
      }
    },
    "systems_2": {
      "locked": {
        "lastModified": 1681028828,
        "narHash": "sha256-Vy1rq5AaRuLzOxct8nz4T6wlgyUR7zLU309k9mBC768=",
        "owner": "nix-systems",
        "repo": "default",
        "rev": "da67096a3b9bf56a91d16901293e51ba5b49a27e",
        "type": "github"
      },
      "original": {
        "owner": "nix-systems",
        "repo": "default",
        "type": "github"
      }
    },
    "treefmt-nix": {
      "inputs": {
        "nixpkgs": [
          "nixpkgs"
        ]
      },
      "locked": {
        "lastModified": 1736154270,
        "narHash": "sha256-p2r8xhQZ3TYIEKBoiEhllKWQqWNJNoT9v64Vmg4q8Zw=",
        "owner": "numtide",
        "repo": "treefmt-nix",
        "rev": "13c913f5deb3a5c08bb810efd89dc8cb24dd968b",
        "type": "github"
      },
      "original": {
        "owner": "numtide",
        "repo": "treefmt-nix",
        "type": "github"
      }
    }
  },
  "root": "root",
  "version": 7
}
```
4. try doing `nix flake check` and it will work
4. execute `nix flake update` to update inputs
5. try `nix flake check` and you should get an output similar to this:
```console
ERRO formatter | goimports: failed to apply with options '[-w]': exit status 2

err: go command required, not found: exec: "go": executable file not found in $PATH: stderr: 
err: go command required, not found: exec: "go": executable file not found in $PATH: stderr: 
err: go command required, not found: exec: "go": executable file not found in $PATH: stderr: 
err: go command required, not found: exec: "go": executable file not found in $PATH: stderr: 
err: go command required, not found: exec: "go": executable file not found in $PATH: stderr: 
```

**Instead of setting up a project from scratch you can also just perform `nix flake check` test before and after `nix flake update` on a real life example: https://github.com/danielmiessler/fabric**

**Expected behavior**
It should work as it worked before

**System information**
NixOS unstable

**Additional context**

**Maintainer ping**
@gabyx

**Comment by gabyx** [comment]
Thanks for the nice bug report.
I also will eventually run into this but have not so far.

Its pretty strange, apparently goimports needs a go executable and didnt before or might it be a packaging problem maybe in goimports? I have to check. So then it also should not work in a simple nix-shell?

**Comment by jaredmontoya** [comment]
What is weird to me is that `nix fmt` still works correctly while `nix flake check` fails like this.

**Comment by gabyx** [comment]
@jaredmontoya : I checked ou current `main` today on https://github.com/danielmiessler/fabric and did a nix flake  update and got the same error: `nix fmt` however works.

The treefmt file which is generated contains (I hope its the same as in `check`): `cat /nix/store/fs6ql36dsjnk2bp9wqrbycvnagxql7hb-treefmt.toml`:

```toml
[formatter.deadnix]
command = "/nix/store/h7jllc8dsyfy1bfhqr3bq1cdxms8ncdn-deadnix-1.2.1/bin/deadnix"
excludes = []
includes = ["*.nix"]
options = ["--edit"]

[formatter.gofmt]
command = "/nix/store/8zgc91q1igzgmg36mglxrk8qa1r2dvsd-go-1.23.6/bin/gofmt"
excludes = ["vendor/*"]
includes = ["*.go"]
options = ["-w"]

[formatter.goimports]
command = "/nix/store/8m595m24h551sa46h60mcbgmz1rqp3j4-gotools-0.30.0/bin/goimports"
excludes = ["vendor/*"]
includes = ["*.go"]
options = ["-w"]

[formatter.nixfmt]
command = "/nix/store/jh6h8md8zl2vsvr6bd3hgldm5p3kcfsl-nixfmt-unstable-2024-12-04/bin/nixfmt"
excludes = []
includes = ["*.nix"]
options = []

[formatter.statix]
command = "/nix/store/xpa3m7f826cmksbxlf5mymwn30zn7wkw-statix-fix/bin/statix-fix"
excludes = []
includes = ["*.nix"]
options = []

[global]
excludes = [
    "*.lock",
    "*.patch",
    "package-lock.json",
    "go.mod",
    "go.sum",
    ".gitignore",
    ".gitmodules",
    ".hgignore",
    ".svnignore",
]
on-unmatched = "warn"
```
When i executre `goimports` from that path it works. Not sure whats going on here.
