### ISSUE TITLE
request: ESLint support

### ISSUE THREAD

**Issue by tennox** [numtide/treefmt-nix#321]
(Originally requested in upstream: https://github.com/numtide/treefmt/discussions/537) 

Would be awesome to have eslint integration - especially with the new formatter rules:
https://eslint.style/

I use https://github.com/antfu/eslint-config for most of my JS projects 👍

**Comment by tennox** [comment]
A simple example:
```toml
[formatter.eslint]
command = "eslint"
options = ["--fix", "--quiet"]
includes = [ "*.js", "*.jsx", "*.ts", "*.tsx" ] # But I'm not sure what to put here, as eslint is able to format MANY files 🤔
excludes = []
```
